apiVersion: v1
kind: Service
metadata:
  name: demo-svc2
  labels:
    app: demo2
spec:
  ports:
    - name: filemanager2
      port: 80
      nodePort: 30001
  selector:
    app: demo2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-depl2
  labels:
    app: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo-filebrowser2
        image: filebrowser/filebrowser
        args: ["--port", "80", "--database", "/database.db", "--scope", "/srv", "--no-auth", "--allow-new=False", "--allow-edit=False"]
        ports:
          - containerPort: 80
        volumeMounts:
          - name: cephfs-mount2
            mountPath: /srv
            subPath: johng/berlin_demo
          - name: cephfs-mount3
            mountPath: /vol3
      volumes:
        - name: cephfs-mount2
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc2
            readOnly: false
        - name: cephfs-mount3
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc3
            readOnly: false
