kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manila-cephfs-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: manila-cephfs-share2
