kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manila-cephfs-pvc3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 42G
  storageClassName: manila-cephfs-share3
